'use client'
import { TaskProvider } from '@/context/TaskContext'
import './globals.css'
import { Inter } from 'next/font/google'
import { Navbar } from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NextJS Content Crud',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TaskProvider>
          <Navbar />
          {children}
        </TaskProvider>
      </body>
    </html>
  )
}
